export const initCast = [
    {
        "id":"1",
        "name": "",
        "origin_name": "Director",
        "slug": "unknow",
        "position_id":2,
    },
    {
        "id":"2",
        "name": "Yao Di",
        "origin_name": "Daji",
        "slug": "daji",
        "position_id":1,
    },
    {
        "id":"3",
        "name": "Wang Qunshi",
        "origin_name": "Leizhenzi",
        "slug": "leizhenzi",
        "position_id":1,
    },
    {
        "id":"4",
        "name": "Qi Wu",
        "origin_name": "Ji Chang",
        "slug": "ji-chang",
        "position_id":1,
    },
    {
        "id":"5",
        "name": "Jing GangshanKing",
        "origin_name": "Zhou of Shang",
        "slug": "zhou-of-shang",
        "position_id":1,
    },
    {
        "id":"6",
        "name": "Kuang Xiao Tong",
        "origin_name": "Moon Shadow",
        "slug": "moon-shadow",
        "position_id":1,
    },
    {
        "id":"7",
        "name": "Wang Jinsong",
        "origin_name": "",
        "slug": "wang-jinsong",
        "position_id":1,
    },
]