export const initMovieType = [
    {
        "id_movie":"1",
        "id_type":"1"
    },
    {
        "id_movie":"1",
        "id_type":"6"
    },
    {
        "id_movie":"2",
        "id_type":"6"
    },
    {
        "id_movie":"2",
        "id_type":"7"
    },
    {
        "id_movie":"3",
        "id_type":"22"
    },
    {
        "id_movie":"3",
        "id_type":"2"
    },
    {
        "id_movie":"3",
        "id_type":"3"
    },
    {
        "id_movie":"4",
        "id_type":"20"
    },
    {
        "id_movie":"4",
        "id_type":"6"
    },
    {
        "id_movie":"5",
        "id_type":"6"
    },
    {
        "id_movie":"5",
        "id_type":"4"
    },
    {
        "id_movie":"7",
        "id_type":"3"
    },
    {
        "id_movie":"7",
        "id_type":"2"
    },
    {
        "id_movie":"7",
        "id_type":"1"
    },
    {
        "id_movie":"7",
        "id_type":"20"
    },
    {
        "id_movie":"8",
        "id_type":"5"
    },
    {
        "id_movie":"8",
        "id_type":"8"
    },
    {
        "id_movie":"9",
        "id_type":"5"
    },
    {
        "id_movie":"9",
        "id_type":"8"
    },
    {
        "id_movie":"10",
        "id_type":"20"
    },
    {
        "id_movie":"10",
        "id_type":"16"
    },
    {
        "id_movie":"10",
        "id_type":"2"
    },
    {
        "id_movie":"10",
        "id_type":"3"
    },
    {
        "id_movie":"10",
        "id_type":"15"
    },
];