export const initMovies = [
    {
        id:"1",
        name: 'Phong Thần: Họa Thương',
        slug: 'phong-than-hoa-thuong',
        origin_name: "League of Gods: The Fall of Sheng 2023",
        publish_date: new Date("2024-01-30"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/z3hBxj5kFoFZNl3Cn8BiUZQq3qW.jpg",
        image: "https://image.tmdb.org/t/p/w185/jHKni0n2bB3oIHv3fyKjOGI0LgS.jpg",
        summary: "Đát Kỷ giam giữ Cơ Xương ở Triêu Ca, mặt khác phái Thân Công Báo thu thập huyền thạch, xây dựng Lộc Đài, mục đích là khiến Yêu vương giáng thế, chấn hưng Yêu tộc, mà Cơ Xương chính là viên huyền thạch cuối cùng. Con trai của Cơ Xương là Lôi Chấn Tử từ nhỏ đã được gửi nuôi ở núi Chung Nam, Lôi Chấn Tử nhận lệnh từ sư phụ đi giải cứu Cơ Xương về Tây Kỳ. Lôi Chấn Tử và Cơ Xương trải qua khó khăn hiểm trở suốt dọc đường, không chỉ gầy dựng được tình cha con thắm thiết mà còn có chung một mục tiêu, đó là lật đổ Trụ vương và Đát Kỷ tàn bạo độc ác, cứu dân chúng khỏi biển lửa…",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "80 Phút",
        status: "completed",
    },
    {
        id:"2",
        name: 'Trò Chơi Bầy Cừu',
        slug: 'tro-choi-bay-cuu',
        origin_name: "Lamb Game 2023",
        publish_date: new Date("2024-01-30"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/lFPIv1fsVBq8NPcSK2gaj4BcQuq.jpg",
        image: "https://image.tmdb.org/t/p/w185/hUeH4rdbREkP4D39uAbb4x2rNl5.jpg",
        summary: "Hồng Kông, 1996. Wang Cui Ying bị bọn cướp bắt làm con tin trong đám cưới của cô và chứng kiến ​​chồng mình chết dưới họng súng của bọn cướp. Không thể thoát ra khỏi sương mù, cô hiện đang làm việc trong một trường bắn cung. Vào đêm bão xảy ra, cô tình cờ ở lại tòa nhà, chứng kiến ​​cùng một nhóm cướp giết hại những người trong đó. Trong khi trốn thoát khỏi họ, cô tình cờ gặp một người mù tên Nan Ge. Kể từ lúc đó, cả hai cố gắng trốn thoát khỏi bọn cướp, trong tòa nhà đã biến thành cạm bẫy chết chóc.",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "88 Phút",
        is_cinema: true,
        status: "completed",
    },
    {
        id:"3",
        name: 'Cô Đi Mà Lấy Chồng Tôi',
        slug: 'co-di-ma-lay-chong-toi',
        origin_name: "Marry My Husband 2023",
        publish_date: new Date("2024-01-17"),
        quality: "HD",
        language: "VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/pT0RwjCRAStJxJBaXZ1gSJV7sVN.jpg",
        image: "https://image.tmdb.org/t/p/w185/JV3DXl1fITfoyHtyPzNuZyzh8q.jpg",
        summary: "Khi Ji-won, một bệnh nhân ung thư 37 tuổi, bước vào gặp chồng và cũng là bạn thân của cô, cô nhận ra cả cuộc đời mình chỉ là một lời nói dối. Tệ hơn nữa, cô lại chết một cách bi thảm dưới tay chồng mình. Liệu mọi chuyện có khác đi nếu cô ấy đưa ra những lựa chọn khác? May mắn thay cho Ji-won, cô có cơ hội viết lại số phận của mình khi được tái sinh thành bản thân lúc trẻ. Lần này, cô thề sẽ sống một cuộc sống hạnh phúc. Nhưng trước hết là sự trả thù. Kế hoạch của cô ấy? Để gả người bạn thân cũ của mình cho người chồng dối trá, lừa dối của mình.",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 2,
        total_episode: 12,
        current_episode: 10,
        status: "ongoing",
    },
    {
        id:"4",
        name: 'Xung Phong Chiến Cảnh',
        slug: 'xung-phong-chien-canh',
        origin_name: "The Constable 2013",
        publish_date: new Date("2024-01-30"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/r3nsOHU7dseQWvpmKXw7WksxUD2.jpg",
        image: "https://image.tmdb.org/t/p/w185/r3nsOHU7dseQWvpmKXw7WksxUD2.jpg",
        summary: "Phim kể về Lâm Quốc Quyền, một cảnh sát sắp nghỉ hưu phải chăm sóc đứa con trai tâm lý không ổn định. Mặc dù vậy ông vẫn hết mình vì công việc, đặt lợi ích của mọi người lên trên hết. Dù là trong giờ làm việc hay ngoài giờ, ông cũng không ngại nguy hiểm luôn xung trận để truy bắt tội phạm.",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "100 Phút",
        is_hot:true,
        status: "completed",
    },
    {
        id:"5",
        name: 'Ma Thổi Đèn: Chín Tầng Tháp Quỷ',
        slug: 'ma-thoi-den-chin-tang-thap-quy',
        origin_name: "Chronicles of the Ghostly Tribe 2023",
        publish_date: new Date("2024-01-26"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/1uVviqJBszPwBex5QE9xVZiDScm.jpg",
        image: "https://image.tmdb.org/t/p/w185/6ae408HIbsYGcor9N4NxSbADI8q.jpg",
        summary: "Năm 1979, trên núi Côn Luân phát hiện hài cốt sinh vật thần bí, Hồ Bát Nhất cùng đoàn thám hiểm tìm kiếm bí mật của di tích cổ trên đó đến được Cửu Tầng Yêu tháp. Nhiều người trong đoàn bỏ mạng trên đường đi hoặc mất tích, không rõ sống chết.Hồ Bát Nhất sau khi giải ngũ trở lại Bắc Kinh, gặp lại bạn thân Vương Khải Tuyền, một lần nữa bước lên hành trình tìm kiếm nền văn minh cổ. Trên đường cùng Shirley Dương tình cờ gặp gỡ, khuôn mặt quen thuộc của cô làm anh nhớ lại những ngày tháng ở cùng đoàn thám hiểm kia. Chuyến đi nguy hiểm, cả đoàn đã bị quái vật tấn công, để rồi nhận ra chuyện phát sinh nơi này lại một lần nữa liên quan đến Cửu Tầng Yêu tháp, mà lần này chờ đợi bọn họ, chính là một bí ẩn chưa có lời đáp đã phủ bụi cả ngàn năm…",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "115 Phút",
        is_cinema: true,
        status: "completed",
    },
    {
        id:"6",
        name: 'Thương Thần Tái Khởi',
        slug: 'thuong-than-tai-khoi',
        origin_name: "Cross The BattLefleld 2023",
        publish_date: new Date("2024-01-26"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/63WYrnNPa2cJkyG27XdwVxQECE0.jpg",
        image: "https://image.tmdb.org/t/p/w185/cBShWaY4gG7rago4mXVX8dj7zJJ.jpg",
        summary: "Cậu học sinh trung học Trầ Vũ Phi yêu thể thao điện tử nhưng chưa bao giờ được người cha ủng hộ. Trong một tai nạn, cha anh và Vương Khải đã hoán đổi danh tính, ban đầu muốn làm xáo trộn sự nghiệp thể thao điện tử của con trai mình, nhưng trong các cuộc thi, họ hiểu nhau, trưởng thành cùng nhau và trở thành bạn thân.",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "88 Phút",
        is_hot:true,
        status: "completed",
    },
    {
        id:"7",
        name: 'Bạch Hồ: Tình Duyên',
        slug: 'bach-ho-tinh-duyen',
        origin_name: "White Fox 2023",
        publish_date: new Date("2024-01-26"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/zqnn3pqQlpzM3F53GqR66U8mL2y.jpg",
        image: "https://image.tmdb.org/t/p/w185/aZ3BFxzNJ79Jn4zG98eLQdOkiJh.jpg",
        summary: "Vụ Sơn Phái và Yêu Tộc vì ân oán từ hàng trăm năm trước mà không ngừng xung đột. Bạch Hồ Tố Tố được giao nhiệm vụ xâm nhập vào Vụ Sơn Phái để cướp lấy viên Đan Luyện Yêu mà Chưởng môn Vụ Sơn Phái An Xích Tiêu đã nỗ lực nghiên cứu để tẩy sạch yêu khí. Tuy nhiên, tai nạn bất ngờ ập tới, Tố Tố đã hấp thụ viên Đan Luyện Yêu, sức mạnh trong cơ thể bị loạn lạc, đánh mất trí nhớ. Cô được thần y Vô Ưu Trại là Hà An Sinh cứu sống. Trong hành trình tìm kiếm danh tính và ký ức, Hà Anh Sinh hiền lành thật thà và cô nương thân thế bí ẩn là Tiểu Bạch (Tố Tố) dần phải lòng nhau. Trong khi đó, viên Đan Luyện Yêu trong cơ thể Tố Tố lại đang tiến tới ranh giới mất kiểm soát. Liệu danh tính thực sự của Tố Tố sẽ bị tiết lộ? Người và yêu có thể đi chung một con đường? Và liệu sau hàng nghìn năm xa cách, giữa người và yêu có được hòa bình chăng?",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "68 Phút",
        is_cinema: true,
        status: "completed",
    },
    {
        id:"8",
        name: 'Khu Rừng Kỳ Quái',
        slug: 'khu-rung-ky-quai',
        origin_name: "The Weird Forest 2023",
        publish_date: new Date("2024-01-22"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/mKvwyvvFTExPHak7nXnLHG6w0mw.jpg",
        image: "https://image.tmdb.org/t/p/w185/enQMcXpL8jqXpQk3oHkWmJ7u8pU.jpg",
        summary: "Mã Hoành Viễn dẫn mọi người vào khu vực cấm của núi Trường Bạch để tìm tàu hỏa, trên đường đi, Bắc Bá Thiên tham lam và ngu ngốc không muốn tuân theo quy tắc của rừng già, trong thời gian nghỉ ngơi, những con búp bê ma đã gây ra náo loạn trong trại. Trong khi chạy trốn, họ gặp một hang động dưới lòng đất, từng tên cướp bị hang động nuốt chửng, Miêu Nữ và Lão Hổ xuất hiện và đưa Mã Hoành Viễn và những người khác rời khỏi khu vực hang động nguy hiểm. Những người sống sót tiếp tục tiến vào làng Long Hưng và phát hiện ra rằng họ đang tổ chức tang lễ. Tên cướp La Cô đã nảy lòng tham, xúc phạm xác chết",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "104 Phút",
        is_hot:true,
        status: "completed",
    },
    {
        id:"9",
        name: 'Trúng Tà',
        slug: 'trung-ta',
        origin_name: "Headless 2023",
        publish_date: new Date("2024-01-22"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/z1jAjjIGzQD3kNcucUN0O94utEF.jpg",
        image: "https://image.tmdb.org/t/p/w185/z1jAjjIGzQD3kNcucUN0O94utEF.jpg",
        summary: "Bộ phim diễn ra vào thời kỳ Trung Hoa Dân quốc, kể về Mục Nguyên đang đối diện với cái chết, trong trí óc, anh ta tự tưởng tượng ra một bản thân mới là cảnh sát Triệu Nhân. Khi Triệu Nhân khám phá ra sự thật đằng sau những sự việc chấn động kỳ quái, Mục Nguyên cũng hoàn thành sự cứu rỗi tâm hồn của mình trước khi qua đời. Với các tình tiết căng thẳng, câu chuyện kể về một câu chuyện triết học xoay quanh việc cứu rỗi tâm hồn. Nó nhằm mục đích truyền tải đến khán giả rằng chỉ có dũng cảm đối mặt với những sai lầm, đau khổ trong quá khứ, chúng ta mới có thể thực sự cởi bỏ những nút thắt bên trong, bước ra khỏi sương mù và giành lại cuộc sống mới.",
        trailer_url: '',
        view: 100,
        share: 0,
        id_category: 1,
        total_episode: 0,
        time: "100 Phút",
        status: "completed",
    },
    {
        id:"10",
        name: 'Chàng Quỷ Của Tôi',
        slug: 'chang-quy-cua-toi',
        origin_name: "My Demon 2023",
        publish_date: new Date("2023-12-06"),
        quality: "HD",
        language:"VIETSUB",
        rating_count: 10,
        rating_point: 43,
        thumb_image: "https://image.tmdb.org/t/p/w500/eSB0fD6CbNW3LT8Z55V07fmYFpo.jpg",
        image: "https://phimmoiiii.net/wp-content/uploads/2023/11/My-Demon.jpg",
        summary: "Chàng Quỷ Của Tôi – My Demon (2023) Do Do Hee là người kế nhiệm của Future Group. Cô ấy có một tính cách kiêu ngạo và lạnh lùng, người không tin tưởng vào bất cứ ai. Cô ấy hoài nghi về tình yêu. Do Do Hee dính líu đến một con quỷ tên là Jung Koo Won và kết hôn theo hợp đồng với anh ta. Cô phải đối mặt với những thay đổi lớn trong cuộc sống của mình.<br><br>Jung Koo Won là một con quỷ. Anh ta có thể sống vĩnh cửu bằng cách thực hiện những giao dịch nguy hiểm, nhưng ngọt ngào với những người chịu đựng cuộc sống địa ngục. Anh ta coi thường con người và anh ta đã rình mò trên thế giới này như một kẻ săn mồi đỉnh cao trong 200 năm. Anh ta dính líu đến Do Do Hee và bằng cách nào đó đột nhiên mất đi sức mạnh của mình. Vnsub.net, Sau đó, anh bước vào một cuộc hôn nhân hợp đồng với cô. Để ngăn chặn sự tuyệt chủng của chính mình, anh phải bảo vệ Do Do Hee, người đã lấy đi tất cả sức mạnh của mình. Mối quan hệ của họ phát triển lãng mạn.",
        trailer_url: '',
        view: 100,
        share: 20,
        id_category: 2,
        total_episode: 16,
        current_episode: 16,
        status: "completed",
    },
];