export const initType = [
  {
    "id": "1",
    "name": "Phim Cổ Trang",
    "slug": "phim-co-trang",
    "description": "Phim Cổ Trang mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.tv, phimhottv.com...",
  },
  {
    "id": "2",
    "name": "Phim Tâm Lý",
    "slug": "phim-tam-ly",
    "description": "Phim Tâm Lý mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "3",
    "name": "Phim Tình Cảm",
    "slug": "phim-tinh-cam",
    "description": "Phim Tình Cảm mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "4",
    "name": "Phim Bí Ẩn",
    "slug": "phim-bi-an",
    "description": "Phim Bí Ẩn mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "5",
    "name": "Phim Kinh Dị",
    "slug": "phim-kinh-di",
    "description": "Phim Kinh Dị mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "6",
    "name": "Phim Hành Động",
    "slug": "phim-hanh-dong",
    "description": "Phim Hành Động mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "7",
    "name": "Phim Võ Thuật",
    "slug": "phim-vo-thuat",
    "description": "Phim Võ Thuật mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "8",
    "name": "Phim Kịch Tính",
    "slug": "phim-kich-tinh",
    "description": "Phim Kịch Tính mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "9",
    "name": "Phim Chiến Tranh",
    "slug": "phim-chien-tranh",
    "description": "Phim Chiến Tranh mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "10",
    "name": "Phim Phiêu Lưu",
    "slug": "phim-phieu-luu",
    "description": "Phim Phiêu Lưu mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "11",
    "name": "Phim Hài",
    "slug": "phim-hai",
    "description": "Phim Phim Hài mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "12",
    "name": "Phim Hình Sự",
    "slug": "phim-hinh-su",
    "description": "Phim Hình Sự mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "13",
    "name": "Phim Gia Đình",
    "slug": "phim-gia-dinh",
    "description": "Gia Đình Ẩn mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "14",
    "name": "Phim Khoa Học",
    "slug": "phim-khoa-hoc",
    "description": "Phim Khoa Học mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "15",
    "name": "Phim Viễn Tưởng",
    "slug": "phim-vien-tuong",
    "description": "Phim Viễn Tưởng mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "16",
    "name": "Phim Netflix",
    "slug": "phim-netflix",
    "description": "Phim Phim Netflix mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": 17,
    "id": "1",
    "name": "Phim Âm Nhạc",
    "slug": "phim-am-nhac",
    "description": "Phim Âm Nhạc mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": 18,
    "id": "1",
    "name": "Phim Thần Thoại",
    "slug": "phim-than-thoai",
    "description": "Phim Thần Thoại mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "19",
    "name": "Phim Hoạt Hình",
    "slug": "phim-hoat-hinh",
    "description": "Phim Hoạt Hình mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "20",
    "name": "Phim Chính Kịch",
    "slug": "phim-chinh-kich",
    "description": "Phim Chính Kịch mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
  {
    "id": "21",
    "name": "TV Shows",
    "slug": "tv-shows",
    "description": "TV Shows mới cập nhật, tuyển tập phim mới hơn 100000+ có phụ đề vietsub thuyết minh chất lượng fullHD tại phimhot.net, phimhottv.com...",
  },
];
